### PR TITLE
Enhancement/issues#14 enable hmr

### LINKED ISSUE #14: validate HMR works as expected

### PR DESCRIPTION
**Pull request by cxoltero**
fixes #14 
@thescientist13 see the following implementation of HMR.
It is as close as it gets without having to manage any sort of state.

### CODE REVIEW

**Comment by cxoltero** [comment]
@thescientist13, this approach is implementing live reload not module replacement, since we are not managing any application state. Otherwise we should add some kind of state store.

**Comment by thescientist13** [comment]
Hmm, then is this really HMR then?  Wasn't livereload something that was already a functioning feature of webpack-dev-server?  Maybe I'm just not clear what this adds to the existing implementation then.

Also, if you could provide this, that might help
> How were you able to arrive at this solution?

**Comment by thisgeek** [comment]
@cxoltero In addition to your answers to @thescientist13's questions, could you explain what you meant by "we are not managing any application state"? I don't see how that's the case. Once there is anything in the UI that would be removed or "forgotten" when the browser refreshes, you can say your UI layer has state. This app has a contact form with field values that would be forgotten on refresh.

**Comment by cxoltero** [comment]
In order for hot reload to work, angular needs to save the application state in a store. The beginning of this repo was intended to do this without a state but, it was only doing a full reload of the app, not hot reload.
As of the last commit, hot reload works implementing a [rxjs](https://github.com/ngrx/platform) store.

@thescientist13 | @thisgeek

**Comment by thescientist13** [comment]
So @cxoltero , still trying to understand how you came to this conclusion?  If it was documented in the README one of those npm dependencies, that's fine, I would just like to be able to link it for those coming to this repo and looking to get more context.

**Comment by paul-barry-kenzan** [comment]
Late to the party, sorry @cxoltero @thescientist13 @thisgeek . 

@cxoltero 
Could you fill me in on a few things so I have a better understanding on the _how_ and _why_ this alternative HMR solution was needed? 

- Why is HMR an issue with Angular, but not with React?
- Where can I read about it in further detail? 
- What prompted you to follow the solution you did?
- Were the other suggested solutions that you tried, but passed on and why?

**Comment by cxoltero** [comment]
Why is HMR an issue with Angular, but not with React?
Hot Module Replacements, when developing we want the app to recompile and show the live changes. hot reload  functionality does this. the idea is that our app keeps its current state, it only shows whatever is changed in the code base.
React has a [react-hot-loader](https://github.com/gaearon/react-hot-loader), implementation and instructions are pretty straight forward. 
Angular 2 uses [angular-hrm](https://github.com/AngularClass/angular-hmr).

Where can I read about it in further detail?
* [webapck hmr](https://webpack.js.org/concepts/hot-module-replacement/)
* [react-hot-loader](https://github.com/gaearon/react-hot-loader)
* [angular-hrm](https://github.com/AngularClass/angular-hmr)

What prompted you to follow the solution you did?
Most of the tools for hrm designed for angular are for version < 2.0, the most documented and used option was [angular-hrm](https://github.com/AngularClass/angular-hmr), which works for any version of angular. The requirements for this is to pass in a store so it know the overall state of the app. react-hot-loader does it by default. 

Were the other suggested solutions that you tried, but passed on and why?
The first solution shown at the beginning of this PR seemed to work because of not clearing cache.

@paul-barry-kenzan | @thescientist13 | @thisgeek

**Comment by thescientist13** [comment]
Thanks for clarifying @cxoltero , very helpful.

One point to follow up on though:
> Why is HMR an issue with Angular, but not with React?

Would one say that because Angular components (HTML / CSS / JS) are "compiled" by the Angular compiler as part of the actual component architecture itself, that is what introduces the technical overhead / abstraction layer for implementing HMR, vs React which is entirely in JavaScript?   

Although in our react repo, the SASS is imported from external files, but my guess is the main difference is that all CSS / HTML in Angular are part of an `@Component` definition, and so thus is an abstraction layer not found in our React HMR implementation?

cc: @paul-barry-kenzan

**Comment by paul-barry-kenzan** [comment]
@cxoltero 
Thanks for the info. I'm less interested in *what* HMR is, and more interested in why Angular HMR is giving us problems. @thescientist13 points out that Angular is "compiled", is that the source of the difficulties?

**Comment by cxoltero** [comment]
@paul-barry-kenzan, In my case, it took me a little time to realize that HMR is not the same as live reload.
Meaning that when  this user story was posted I assumed we were only required to implement a reload of the app when the codebase changed (which we were already doing via web pack hotModuleReplacement).
Once this was addressed, implementing HMR in Angular just needed a little bit more configuration, such configuration includes just adding a single store to watch/pass in and, implement observables in that store.

@thescientist13  | @thisgeek

**Comment by thescientist13** [comment]
Hello friends @paul-barry-kenzan / @cxoltero !

So just wanted to close the loop on this.

## HMR Exercise Example
I don't see this as working @cxoltero, can you please confirm.  If I'm following the reader exercise steps from the [article](https://www.linux.com/blog/learn/2017/8/all-stacked-case-study) (paraphrased) I'm not able to get the same experience
1. Clicked Add contact to display the form for adding a new contact
2. Filled out the First Name field with my name
3. Changed the background color to blue

**Expected**:
The background would turn blue, and my name would stay in the input field

**Actual**:
The app entirely reloaded and I had to click again Add contact again.  My name was lo longer in the input field.

screen shot 2017-09-08 at 9 31 45 am


## HMR Explanation
So I can open a new PR and provide the context I think would be needed for anyone coming to this project and looking to our HMR example and in reviewing all the comments so far, this is how I plan on documenting the implementation (once it's working and meets the expectations of the what is documented in the article series)

> As seen here, the implementation of Angular HMR is definitely more complicated compared to the implementation needed / seen in our comparable React repository [react-webpack-stack](https://github.com/kenzanlabs/react-webpack-stack).  This complexity likely comes down to React being entirely in JavaScript, while Angular is compiling down HTML, CSS, and JavaScript.   This is what lead us to follow the steps [here](https://github.com/AngularClass/angular-hmr) for getting our application running with webpack + HMR.
>
> This implementation introduces the concept of a store (similar to the concept of a store in Flux / Redux) which manages the state of our application and makes it part of our `AppModule`.  This store was then integrated into various parts of our application, like in our `Home` view.

**Comment by thescientist13** [comment]
Hey @cxoltero , just checking to see if there are any updates here to check out, re: my last comment?  Thanks!

**Comment by cxoltero** [comment]
@thescientist13 | @paul-barry-kenzan 

as of 029f411 This pr contains the functionality expected per @thescientist13 comment on "HMR Exercise Example".

There is another bug present.
steps to reproduce:
  * navigate to http://localhost:9000/
  * add two contacts
  * make a code change case 'background-color'

expected behavior.
 * when user clicks on either contact button, the contact information component gets updated.
actual behavior.
 * contact buttons do not show clickable behavior.

Opening ticket for that issue.

**Comment by thescientist13** [comment]
thanks for the update @cxoltero and reporting the issue you found .  will test it out.

**Comment by thescientist13** [comment]
@cxoltero 
Actually, just realized since this PR isn't ever going to be merged, that the issue only needs to be called out here, so I will close that issue, and factor it into the new PR we will open

**Pull request closed without merging**
